#!/usr/bin/env bash

if [[ -n `csrutil status | grep "disabled"` ]]; then
  brew cask install asepsis
else
  echo "You must disable System Integrety Protection to install Asepsis.\nReboot into recovery mode (Command+R during startup) and run 'csrutil disable' from Terminal while in recovery mode." && exit 1
fi

sudo find / -name *.DS_Store -depth -exec rm {} \;

defaults write com.apple.Finder FXPreferredViewStyle Nlsv

defaults write -g AppleShowAllExtensions -bool true

defaults write com.apple.finder AppleShowAllFiles true

chflags nohidden ~/Library

defaults read com.apple.finder NewWindowTargetPath -string file:///Users/`whoami`

defaults write com.apple.finder FXDefaultSearchScope -string SCcf

defaults write com.apple.finder ShowPathbar -bool true
defaults write com.apple.finder ShowStatusBar -bool true
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

defaults write com.apple.finder ShowTabView -bool true

defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowMountedServersOnDesktop -bool false
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool false

defaults write com.apple.finder ShowPreviewPane -bool true
defaults write com.apple.finder PreviewPaneWidth -int 172

defaults write com.apple.finder SidebarWidth -int 172

defaults delete com.apple.sidebarlists networkbrowser
defaults write com.apple.sidebarlists networkbrowser -array-add '<dict><key>CustomListItems</key><array/><key>CustomListProperties</key><dict><key>com.apple.NetworkBrowser.connectedEnabled</key><true/><key>com.apple.NetworkBrowser.bonjourEnabled</key><false/><key>com.apple.NetworkBrowser.backToMyMacEnabled</key><true/></dict><key>Controller</key><string>CustomListItems</string></dict>'

killall Finder
rm ~/Library/Application\ Support/Dock/*.db
killall Dock

defaults write -g NSNavPanelExpandedStateForSaveMode -bool true
defaults write -g NSNavPanelExpandedStateForSaveMode2 -bool true

defaults write com.apple.dock tilesize -int 48
defaults write com.apple.dock size-immutable -bool true
killall Dock

defaults write com.apple.dock showhidden -boolean true
killall Dock

defaults delete com.apple.dock persistent-apps
killall Dock

defaults write com.apple.dock persistent-apps -array-add '{tile-data={}; tile-type="spacer-tile";}'
killall Dock

defaults write com.apple.dock springboard-show-duration -float 0.1
defaults write com.apple.dock springboard-hide-duration -float 0.11
defaults write com.apple.dock springboard-page-duration -float 0.1

defaults write com.apple.dock springboard-columns -int 8
defaults write com.apple.dock springboard-rows -int 12
defaults write com.apple.dock ResetLaunchPad -bool true

defaults write com.apple.dock mru-spaces -bool false

defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false
echo "You may have to logout and log back in for this change to take effect."

defaults write -g ApplePressAndHoldEnabled -bool false
defaults write -g InitialKeyRepeat -float 50
defaults write -g KeyRepeat -float 1

sudo spctl --master-disable

defaults write com.apple.CrashReporter UseUNC 1

defaults write com.apple.screencapture disable-shadow -bool true
killall SystemUIServer

defaults write -g NSScrollAnimationEnabled -bool false

defaults write -g NSAutomaticWindowAnimationsEnabled -bool false

defaults write -g QLPanelAnimationDuration -float 0

defaults write -g NSWindowResizeTime -float 0.001

defaults write com.apple.finder DisableAllAnimations -bool true

defaults write com.apple.dock launchanim -bool false

defaults write com.apple.dock expose-animation-duration -float 0.1

defaults write -g NSDocumentRevisionsWindowTransformAnimation -bool false

defaults write -g NSScrollViewRubberbanding -bool false

defaults write com.apple.dock autohide-time-modifier -float 0

defaults write com.apple.dock autohide-delay -float 0.1

defaults write -g NSBrowserColumnAnimationSpeedMultiplier -float 0.001

defaults write -g NSToolbarFullScreenAnimationDuration -float 0.001

defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
